name: 'Fetch & Ingest 2019-nCov/SARS-CoV-2 data from GISAID for nextstrain.org/ncov'

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # "At 08:00 (10:00 CET) on every day-of-week from Monday through Friday."
    - cron:  '0 8 * * MON-FRI'

  # Manually triggered using `./bin/trigger fetch-and-ingest`
  repository_dispatch:
    types: fetch-and-ingest

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: ingest
      run: |
        PATH="$HOME/.local/bin:$PATH"
        python3 -m pip install --upgrade pip setuptools
        python3 -m pip install pipenv
        pipenv sync
        pipenv run ./bin/ingest-gisaid --fetch
      env:
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GISAID_API_ENDPOINT: ${{ secrets.GISAID_API_ENDPOINT }}
        GISAID_USERNAME_AND_PASSWORD: ${{ secrets.GISAID_USERNAME_AND_PASSWORD }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        SLACK_CHANNELS: ncov-gisaid-updates
