name: GenBank ingest (on branch)

on:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - '**'

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: ingest
      run: |
        PATH="$HOME/.local/bin:$PATH"

        python3 -m pip install nextstrain-cli

        ./bin/write-envdir env.d \
          AWS_DEFAULT_REGION \
          GITHUB_REF \
          SLACK_TOKEN

        nextstrain build \
          --aws-batch \
          --image nextstrain/ncov-ingest \
          --cpus 8 \
          --memory 15GiB \
          --exec env \
          . \
            envdir env.d ingest-genbank
      env:
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
