name: Rebuild nextstrain.org/staging/ncov

on:
  # Manually triggered using bin/trigger rebuild
  repository_dispatch:
    types: rebuild

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: rebuild
      run: |
        PATH="$HOME/.local/bin:$PATH"
        python3 -m pip install --upgrade pip setuptools
        python3 -m pip install pipenv
        pipenv sync
        pipenv run ./bin/rebuild-staging
      env:
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_INCOMING_WEBHOOK }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
