name: Rebuild nextstrain.org/ncov

on:
  # Manually triggered using bin/trigger rebuild
  repository_dispatch:
    types: rebuild

  # Manually triggered using GitHub's UI
  workflow_dispatch:

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: setup
      run: ./bin/setup-github-workflow

    - name: rebuild-gisaid-data
      run: ./bin/rebuild gisaid
      env:
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        SLACK_CHANNELS: ncov-gisaid-updates

    - name: rebuild-genbank-data
      run: ./bin/rebuild genbank
      env:
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        SLACK_CHANNELS: ncov-genbank-updates
